# Generated by Django 4.0 on 2023-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
