# Generated by Django 4.0 on 2023-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
